name: 'insuraflow_dbt'
version: '1.0.0'
config-version: 2

profile: 'insuraflow_dbt'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  insuraflow_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table
