log_file: D:/Data Engineering Prep/Pyspark/logs/pipeline.log

paths:
  raw_data: D:/Data Engineering Prep/Pyspark/input/insurance_data.json
  cleaned_data: D:/Data Engineering Prep/Pyspark/output/cleaned_insurance_data.json
  transformed_data: D:/Data Engineering Prep/Pyspark/output/transformed_insurance_data.json

notebooks:
  cleaning:
    input: D:/Data Engineering Prep/Pyspark/notebooks/cleaning/data_cleaning.ipynb
    output_temp: D:/Data Engineering Prep/Pyspark/notebooks/cleaning/temp_cleaned.ipynb

  transforming:
    input: D:/Data Engineering Prep/Pyspark/notebooks/transforming/data_transformer.ipynb
    output_temp: D:/Data Engineering Prep/Pyspark/notebooks/transforming/temp_transformed.ipynb